name: Daily DA Auction Update

on:
  schedule:
    - cron: '15 13 * * *'  # Runs at 15:15 Paris time (13:15 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the script
        run: python Asset_Modeling/Energy_Modeling/ShortTerm_Power/DA_AuctionFR.py
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Commit and push updated Excel file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Data/DA_PriceFR.xlsx
          git commit -m "Update DA_PriceFR.xlsx [auto]" || echo "No changes to commit"
          git push
